#!/usr/bin/env bash
# Interactive menu to use the Proxmox Helper Toolkit

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
PHT_DIR="$SCRIPT_DIR/pht-files/"
TRACK_FILE="$SCRIPT_DIR/.pht_scripts"

# -------------------------
# Source bash-tui-toolkit
# -------------------------

if ! [[ -f $PHT_DIR/_bash-tui-toolkit.bash ]]; then
    if ! curl -fsSL https://bash-tui-toolkit.timo-reymann.de/latest/bundle.bash -o "$PHT_DIR/_bash-tui-toolkit.bash"; then
        echo "Failed downloading bash-tui-toolkit"
        exit 1
    fi
fi
# shellcheck disable=SC1091
source "$PHT_DIR/_bash-tui-toolkit.bash"

# -------------------------
# Check for install
# -------------------------

if [[ ! -f "$TRACK_FILE" ]]; then
    show_error "Install Proxmox Helper Toolkit using pht-updater before running this script"
    read -rp "Press enter to continue..."
fi

# -------------------------
# Global storage
# -------------------------

declare -A META
declare -a ACTIONS
declare -A ACTION_DATA
declare -A FIELD_DATA
declare -A OPTION_DATA
declare -A FLAG_DATA


# -------------------------
# Helpers
# -------------------------

trim() {
    echo "$1" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//'
}


clean_value() {
    local value="$1"

    value="$(trim "$value")"
    value="${value#\"}"
    value="${value%\"}"

    echo "$value"
}


_metadata() {
    META=()
    ACTIONS=()

    ACTION_DATA=()
    FIELD_DATA=()
    OPTION_DATA=()
    FLAG_DATA=()
}


# -------------------------
# .pht parser
# -------------------------

parse_pht() {

    _metadata

    local file="$1"

    local section=""
    local action=-1
    local field=-1
    local option=-1
    local flag=-1


    while IFS= read -r line || [[ -n "$line" ]]; do

        # Remove comments
        line="${line%%#*}"

        line="$(trim "$line")"

        [[ -z "$line" ]] && continue


        case "$line" in

            "[action]")
                section="action"

                ((action++))

                field=-1
                option=-1
                flag=-1

                ACTIONS+=("$action")
                ;;


            "[/action]")
                section=""
                ;;


            "[field]")
                section="field"

                ((field++))
                option=-1
                ;;


            "[/field]")
                section="action"
                ;;


            "[option]")
                section="option"

                ((option++))
                ;;


            "[/option]")
                section="field"
                ;;


            "[flag]")
                section="flag"

                ((flag++))
                ;;


            "[/flag]")
                section="action"
                ;;


            "[confirm]")
                section="confirm"
                ;;


            "[/confirm]")
                section="action"
                ;;


            *)
                key="${line%%=*}"
                value="${line#*=}"

                key="$(trim "$key")"
                value="$(clean_value "$value")"


                case "$section" in

                    "")
                        META["$key"]="$value"
                        ;;


                    action)
                        ACTION_DATA["$action:$key"]="$value"
                        ;;


                    field)
                        FIELD_DATA["$action:$field:$key"]="$value"
                        ;;


                    option)
                        OPTION_DATA["$action:$field:$option:$key"]="$value"
                        ;;


                    flag)
                        FLAG_DATA["$action:$flag:$key"]="$value"
                        ;;


                    confirm)
                        ACTION_DATA["$action:confirm:$key"]="$value"
                        ;;

                esac
                ;;

        esac

    done < "$file"
}

# -------------------------
# Load entries
# -------------------------

load_entries() {

    menu_entries=()

    for pht in "$PHT_DIR"/*.pht; do

        [[ -f "$pht" ]] || continue

        entry="$(basename "$pht" .pht)"

        parse_pht "$pht"

        [[ "${META[hidden]}" == "true" ]] && continue

        menu_entries+=("$entry")

    done

    mapfile -t menu_entries < <(printf "%s\n" "${menu_entries[@]}" | sort)
}

# -------------------------
# Select entry
# -------------------------

select_entry() {

    local display_entries=()
    local entry_names=()

    for entry in "${menu_entries[@]}"; do

        parse_pht "$PHT_DIR/$entry.pht"

        title="${META[title]:-$entry}"
        description="${META[description]}"

        if [[ -n "$description" ]]; then
            display_entries+=("$title -- $description")
        else
            display_entries+=("$title")
        fi

        entry_names+=("$entry")

    done

    selected=$(list "Select entry" "${display_entries[@]}")

    echo "${entry_names[$selected]}"
}

# -------------------------
# Select action
# -------------------------

select_action() {

    local visible=()
    local indexes=()

    for action in "${ACTIONS[@]}"; do

        hidden="${ACTION_DATA[$action:hidden]}"

        [[ "$hidden" == "true" ]] && continue


        visible+=("${ACTION_DATA[$action:name]}")
        indexes+=("$action")

    done

    [[ ${#visible[@]} -gt 0 ]] || return 1

    for action in "${indexes[@]}"; do

        if [[ "${ACTION_DATA[$action:default]}" == "true" ]]; then
            echo "$action"
            return
        fi

    done

    selected=$(list "${META[title]}" "${visible[@]}")

    echo "${indexes[$selected]}"
}


# -------------------------
# Collect flags
# -------------------------

collect_flags() {
    FLAGS=()

    local action="$1"

    for ((i=0; ; i++)); do

        name="${FLAG_DATA[$action:$i:name]}"

        [[ -z "$name" ]] && break

        flag_arguments="${FLAG_DATA[$action:$i:arguments]}"

        answer=$(confirm "$name")

        if [[ "$answer" == "1" ]]; then
            flag_array=()

            eval "flag_array=($flag_arguments)"
            FLAGS+=("${flag_array[@]}")
        fi

    done
}


# -------------------------
# Collect fields
# -------------------------

collect_fields() {
    FIELDS=()

    local action="$1"

    for ((field=0; ; field++)); do

        name="${FIELD_DATA[$action:$field:name]}"

        [[ -z "$name" ]] && break

        type="${FIELD_DATA[$action:$field:type]}"

        case "$type" in

            input|path|ipv4|number)

                value=$(input "$name")
                ;;

            password)

                value=$(password "$name")
                ;;

            list)

                options=()
                values=()


                for ((option=0; ; option++)); do

                    option_name="${OPTION_DATA[$action:$field:$option:name]}"

                    [[ ! -v "OPTION_DATA[$action:$field:$option:name]" ]] && break

                    options+=("$option_name")
                    values+=("${OPTION_DATA[$action:$field:$option:value]}")

                done

                selected=$(list "$name" "${options[@]}")

                value="${values[$selected]}"

                ;;

            *)

                value=$(input "$name")

                ;;

        esac

        FIELDS+=("$value")

    done
}


# -------------------------
# Execute
# -------------------------

run_action() {

    local action="$1"

    collect_flags "$action"
    collect_fields "$action"

    confirm_message="${ACTION_DATA[$action:confirm:message]}"

    if [[ -n "$confirm_message" ]]; then

        answer=$(confirm "$confirm_message")

        clear
        [[ "$answer" == "1" ]] || return
    fi

    args=()

    # Add flags first
    args+=(
        "${FLAGS[@]}"
    )

    # Add action arguments
    action_arguments="${ACTION_DATA[$action:arguments]}"

    if [[ -n "$action_arguments" ]]; then

        argument_array=()

        eval "argument_array=($action_arguments)"

        args+=("${argument_array[@]}")

    fi

    # Add user supplied fields last
    args+=(
        "${FIELDS[@]}"
    )

    command="${ACTION_DATA[$action:command]}"

    if ! command -v "$command" >/dev/null 2>&1; then
        show_error "Command not found: $command"
        read -rp "Press enter to continue..."
        return
    fi

    printf 'Running: %q' "$command"
    printf ' %q' "${args[@]}"
    echo

   "$command" "${args[@]}"

    exit_code=$?

    if [[ $exit_code -ne 0 ]]; then
        show_error "$command failed with exit code $exit_code"

    else
        show_success "$command completed successfully"

    fi

    read -rp "Press enter to continue..."
    clear
}

# -------------------------
# List entries
# -------------------------

list_entries() {

    for pht in "$PHT_DIR"/*.pht; do

        [[ -f "$pht" ]] || continue

        entry_name="$(basename "$pht" .pht)"

        parse_pht "$pht"

        # Skip hidden entries
        [[ "${META[hidden]}" == "true" ]] && continue

        title="${META[title]:-$entry_name}"
        description="${META[description]}"

        printf "\e[33m%s\e[0m\n" "$title"
        [[ -n "$description" ]] && printf "  %s\n" "$description"
        echo
    done
}

# -------------------------
# Remove Proxmox Helper Toolkit
# -------------------------

remove_installation() {

    [[ -f "$TRACK_FILE" ]] || {
        show_error "No Proxmox Helper Toolkit installation found"
        return 1
    }

    while IFS= read -r trackfile_entry; do
        [[ -z "$trackfile_entry" ]] && continue
        [[ "$trackfile_entry" == "$SCRIPT_NAME" ]] && continue

        rm -f "$SCRIPT_DIR/$trackfile_entry"

    done < "$TRACK_FILE"

    rm -f "$TRACK_FILE"
    rm -rf "$PHT_DIR"
    rm -rf "$0"

    show_success "Proxmox Helper Toolkit removed"
}

# -------------------------
# Load Menu
# -------------------------

open_menu() {
    while true; do
        echo "Loading..."

        load_entries && clear

        [[ ${#menu_entries[@]} -gt 0 ]] || {
            show_error "No entries found"
            exit 1
        }

        menu_entry=$(select_entry) && clear

        parse_pht "$PHT_DIR/$menu_entry.pht"


        action=$(select_action) && clear

        run_action "$action"

    done
}

# -------------------------
# Main
# -------------------------

clear

case "${1:-}" in

    list)
        list_entries
        exit $?
        ;;

    remove)
        remove_installation
        exit $?
        ;;

    "")
        open_menu
        exit $?
        ;;


    *)
        show_error "Unknown command: $1"
        echo
        echo "Usage:"
        echo "  $SCRIPT_NAME          Open menu"
        echo "  $SCRIPT_NAME list     List installed scripts"
        echo "  $SCRIPT_NAME remove   Remove Proxmox Helper Toolkit"
        exit 1
        ;;
esac
