#!/usr/bin/env bash
# Lists installed Proxmox Helper Toolkit scripts and descriptions

SCRIPT_NAME="$(basename "$0")"
SCRIPT_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
TRACK_FILE="$SCRIPT_DIR/.pht_scripts"

# Source bash-tui-toolkit
if ! [[ -f $SCRIPT_DIR/.bash-tui-toolkit.bash ]]; then
    if ! curl -fsSL https://bash-tui-toolkit.timo-reymann.de/latest/bundle.bash -o "$SCRIPT_DIR/.bash-tui-toolkit.bash"; then
        echo "Failed downloading bash-tui-toolkit"
        exit 1
    fi
fi
source "$SCRIPT_DIR/.bash-tui-toolkit.bash"

# Functions
error_exit() {
    echo "Error: $1" >&2
    exit 1
}

# Checks
if [[ ! -f "$TRACK_FILE" ]]; then
    error_exit "Install Proxmox Helper Toolkit using pht-updater before running this script"
fi

# List scripts
while IFS= read -r SCRIPT; do
    [[ -z "$SCRIPT" ]] && continue

    FILE="$SCRIPT_DIR/$SCRIPT"

    if [[ -f "$FILE" ]]; then
        DESCRIPTION=$(sed -n '2p' "$FILE")

        echo "$(tput setaf 3)$SCRIPT$(tput sgr0)"
        echo "  ${DESCRIPTION:-No description}"
        echo
    fi
done < "$TRACK_FILE"
