#!/bin/bash
# Updates everything on the Proxmox node

# shellcheck disable=SC2016

echo "After the update;"
read -rp "Remove old packages after updating? (y/N): " answer_remove
read -rp "Reboot the node after updating? (y/N): " answer_reboot

echo "Updating all running containers..."
bash -c 'var_backup=no var_container=all_running var_unattended=yes var_skip_confirm=yes var_auto_reboot=yes bash -c "$(curl -fsSL https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/tools/pve/update-apps.sh)"'

echo "Updating system packages..."
bash -c 'apt --assume-yes update && apt --assume-yes upgrade'

case "$answer_remove" in
    [yY]|[yY][eE][sS])
        echo "Removing old system packages..."
        run_command "apt --assume-yes autoremove"
        ;;
esac

echo "Node update complete"

case "$answer_reboot" in
    [yY]|[yY][eE][sS])
        bash -c 'reboot'
        ;;
    *)
        exit 0
        ;;
esac